- hosts: all
  tasks:

    - name: "On s'assure que pip soit installé"
      package:
        name: python3-pip

    - name: On check les packages python
      community.general.pip_package_info:
        clients:
          - pip3
        
